server:
  port: 8090
  error:
    whitelabel:
      enabled: false

# Set here configurations for the database connection
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/dbsistemasecurity
    username: root
    password: Mar14D3
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB


# Ruta de archivos
ejemplo:
  imagen:
    ruta: "c:/imagenes/"


# LOGGING LEVEL
logging:
  level:
    root: INFO
    com.itextpdf.styledxmlparser.css.parse.CssRuleSetParser: off

# JWT
jwt:
  secret: 5f39c83d2d0482e07b5306f3f5a0fd8e1b4e9844987121ba4b99f3f4805fd4f85cc0f24ece8556dd10456a45d20cd2d61e7c36a77583674be979b071b869f34f
  expirationDateInMs: 3600
  refreshExpirationDateInMs: 900